### ISSUE TITLE
Sentence Case not working for me?

### ISSUE THREAD

**Issue by sts10** [vmdanilov/TextFlow#3]
When I select Title Case it transforms to title case no problem, but then, on the same text, when I select Sentence Case from the transform menu nothing happens. By contrast, transforming to lower case and then sentence case it seems to work. I tried it in Chrome in GMail and Twitter. Am I just doing something dumb?

**Comment by vmdanilov** [comment]
No, my bad. Sentence Case should lowercase first. Fixing it now.
